name: counter_app
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <3.5.0"  # Adjusted to match your current Dart SDK version (3.4.3)

dependencies:
  # Existing dependencies
  async: 2.11.0
  boolean_selector: 2.1.1
  characters: 1.3.0
  # Add other dependencies similarly

dependency_overrides:
  async: 2.11.0
  boolean_selector: 2.1.1
  characters: 1.3.0
  clock: 1.1.1
  collection: 1.18.0
  # List all packages that show as outdated


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2
  flutter_lints: ^4.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "lib/assets/icon/icon.png" # Adjusted to remove the extra space

flutter:
  uses-material-design: true

  assets:
    - lib/assets/
